eno=int(input('enter employee No: '))
ename=input('enter employee name: ')
esal=int(input('enter employee salary: '))
eaddr=input('enter employee address: ')
married=bool(input('employee married ?[True|False]: '))
print()
print('Please confirm information')
print('Employee No:',eno)
print('employee name:',ename)
print('employee salary:',esal)
print('employee address:',eaddr)
print('employee married ? :', married)